baseurl = "https://lts.eclipse.org/"
DefaultContentLanguage = "en"
title = "Eclipse LTS"
theme = "eclipsefdn-hugo-solstice-theme"
metaDataFormat = "yaml"
#googleAnalytics = "U"
disableKinds = []
themesDir = "node_modules/"
enableRobotsTXT = true
pluralizeListTitles = false

[Params]
  google_tag_manager = "GTM-5WLCZXC"
  description = "Eclipse LTS enables long term maintenance for Eclipse technologies to help adopters to stay on top of regular software updates to avoid problems upfront, as well as to react to problems that impede users."
  seo_title_suffix = " | The Eclipse Foundation"
  keywords = ["eclipse lts", "lts", "open source lts", "eclipse lts"]
  gcse = "011805775785170369411:p3ec0igo0qq"
  js = "js/solstice.js"
# logo = ""
# styles = "css/styles.css"
# favicon = ""
# share_img = ""
header_wrapper_class = "header-default-bg-img"
# logo_width = ""
# header_left_classes = ""
# main_menu_wrapper_classes = ""

[taxonomies]
  category = "categories"
  tag = "tags"
  membership_level = "membership_levels"
  participation_level = "participation_levels"

[Author]
  name = "Christopher Guindon"
  website = "https://www.eclipse.org"
  email = "webdev@eclipse-foundation.org"
  facebook = "eclipse.org"
  twitter = "EclipseFdn"
  youtube = "EclipseFdn"
  googleplus = "+Eclipse"
  linkedin = "company/eclipse-foundation/"

[permalinks]
  news = "/:sections/:year/:month/:day/:slug/"

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 1

