baseurl = "https://lts.eclipse.org/"
DefaultContentLanguage = "en"
title = "Eclipse LTS"
theme = "eclipsefdn-hugo-solstice-theme"
metaDataFormat = "yaml"
#googleAnalytics = "U"
disableKinds = []
themesDir = "node_modules/"
enableRobotsTXT = true
pluralizeListTitles = false

[Params]
  google_tag_manager = "GTM-5WLCZXC"
  description = "Eclipse LTS enables long term maintenance for Eclipse technologies to help adopters to stay on top of regular software updates to avoid problems upfront, as well as to react to problems that impede users."
  seo_title_suffix = " | The Eclipse Foundation"
  keywords = ["eclipse lts", "lts", "open source lts", "eclipse lts"]
  gcse = "011805775785170369411:p3ec0igo0qq"
  js = "js/solstice.js"
# logo = ""
# styles = "css/styles.css"
# favicon = ""
# share_img = ""
  header_wrapper_class = "header-default-bg-img"
# logo_width = ""
# header_left_classes = ""
# main_menu_wrapper_classes = ""

[taxonomies]
  category = "categories"
  tag = "tags"
  membership_level = "membership_levels"
  participation_level = "participation_levels"

[Author]
  name = "Christopher Guindon"
  website = "https://www.eclipse.org"
  email = "webdev@eclipse-foundation.org"
  facebook = "eclipse.org"
  twitter = "EclipseFdn"
  youtube = "EclipseFdn"
  googleplus = "+Eclipse"
  linkedin = "company/eclipse-foundation/"

[permalinks]
  news = "/:sections/:year/:month/:day/:slug/"

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true

[[menu.main]]
  name = "Projects"
  url = "/projects/"
  weight = 1

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 2

[[menu.main]]
  name = "Resources"
  url = "/resources/"
  weight = 3

[[menu.main]]
  name = "FAQ"
  url = "/about/faq/"
  weight = 4

#######################

[[menu.sidebar]]
  name = "GET SUPPORT"
  weight = 1
  identifier = "home"

[[menu.sidebar]]
  parent = "home"
  name = "Subscribe"
  url = "https://accounts.eclipse.org/mailing-list/lts-iwg"
  weight = 2
  identifier = "subscribe"

[[menu.sidebar]]
  parent ="home"
  name = "Get help"
  url = "/about/request-help/"
  weight = 3
  identifier = "get-help"

#################################

[[menu.sidebar]]
  name = "LTS FLYOVER"
  weight = 4
  identifier = "flyover"

[[menu.sidebar]]
  parent = "flyover"
  name = "How It Works?"
  url = "/about/how-does-it-work/"
  weight = 5
  identifier = "how-does-it-work"

[[menu.sidebar]]
  parent ="flyover"
  name = "Business Opportunities"
  url = "/about/business-opportunities/"
  weight = 6
  identifier = "business-opportunities"

[[menu.sidebar]]
  parent ="flyover"
  name = "Criteria for being LTS ready"
  url = "/about/criteria-being-lts-ready/"
  weight = 7
  identifier = "criteria-being-lts-ready"

[[menu.sidebar]]
  parent ="flyover"
  name = "LTS Infrastructure"
  url = "/about/infrastructure/"
  weight = 8
  identifier = "infrastructure"

[[menu.sidebar]]
  parent ="flyover"
  name = "Need Help With An Older Release?"
  url = "/about/request-help/"
  weight = 9
  identifier = "request-help"

######################